version: '3.4'

services:
  easydev:
    image: easydev
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: production-stage
    environment:
      - NODE_ENV=production
