services:
  easydev:
    image: easydev
    build: 
      context: ../../../
      dockerfile: tools/jenkins/build/Dockerfile
      target: production-stage
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"
